### PR TITLE
US004 - Fixes for The Job Constructor

### PR DESCRIPTION
**Pull request by CharlesM988**
Consolidated the Job class.

- Fixes to the Job Model to flow better with the table on the database.
- Fixes to the JobDao.

### CODE REVIEW

**Comment by amchugh689** [comment]
breaks the tests, will push a fix

**Review by eoinmcbennett — APPROVED** [review]
Looks grand.

**Review by Cormac-F — APPROVED** [review]
LGTM

**Review by eoinmcbennett — APPROVED** [review]
Looks good.

**Pull request merged**
