### PR TITLE
US002 View Job Spec for Each Role - API

### PR DESCRIPTION
**Pull request by CharlesM988**
- Created JobService.java
- Created JobController.java
- Created JobDao.java
- Created Job.java
- Created JobSpecDoesNotExistException.java
- Created FailedToGetJobSpecException.java

Screenshot 2023-12-12 at 11 10 22

### CODE REVIEW

**Review by Cormac-F — APPROVED** [review]
LGTM

**Review by jkelso662 — DISMISSED** [review]
Looks like your build is failing! Better check that out. Also it's a real shame there are no unit tests in here 😢

**Comment by CharlesM988** [comment]
@jkelso662 fixes made and the branch is now building successfully.

**Comment by lullabelle** [comment]
Are there any unit tests for this PR? And where is my name???!

**Comment by CharlesM988** [comment]
@lullabelle yes there are a few unit tests and some integration tests too. 

Screenshot 2023-12-14 at 14 34 51
Screenshot 2023-12-14 at 14 35 05
Screenshot 2023-12-14 at 14 35 31

**Review by lullabelle — APPROVED** [review]
Approved. I couldnt see the unit tests in the repo but thanks for the screenshots

**Comment by CharlesM988** [comment]
> Approved. I couldnt see the unit tests in the repo but thanks for the screenshots

@lullabelle I wasn't sure if the tests should be pushed up to the repo or not!

**Pull request merged**
